// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CompatibilityEdgeDependency.
const (
	Dev      CompatibilityEdgeDependency = "dev"
	Required CompatibilityEdgeDependency = "required"
	Soft     CompatibilityEdgeDependency = "soft"
)

// Valid indicates whether the value is a known member of the CompatibilityEdgeDependency enum.
func (e CompatibilityEdgeDependency) Valid() bool {
	switch e {
	case Dev:
		return true
	case Required:
		return true
	case Soft:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for Language.
const (
	Elixir     Language = "elixir"
	Go         Language = "go"
	Python     Language = "python"
	Ruby       Language = "ruby"
	Rust       Language = "rust"
	Typescript Language = "typescript"
)

// Valid indicates whether the value is a known member of the Language enum.
func (e Language) Valid() bool {
	switch e {
	case Elixir:
		return true
	case Go:
		return true
	case Python:
		return true
	case Ruby:
		return true
	case Rust:
		return true
	case Typescript:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	Internal         ProblemCode = "internal"
	MethodNotAllowed ProblemCode = "method_not_allowed"
	NotFound         ProblemCode = "not_found"
	Unavailable      ProblemCode = "unavailable"
	ValidationFailed ProblemCode = "validation_failed"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case Internal:
		return true
	case MethodNotAllowed:
		return true
	case NotFound:
		return true
	case Unavailable:
		return true
	case ValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	ReadinessStatusOk ReadinessStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case ReadinessStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryDefaultBranch.
const (
	Master RepositoryDefaultBranch = "master"
)

// Valid indicates whether the value is a known member of the RepositoryDefaultBranch enum.
func (e RepositoryDefaultBranch) Valid() bool {
	switch e {
	case Master:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryVisibility.
const (
	Private RepositoryVisibility = "private"
	Public  RepositoryVisibility = "public"
)

// Valid indicates whether the value is a known member of the RepositoryVisibility enum.
func (e RepositoryVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for ServiceKind.
const (
	API    ServiceKind = "api"
	Both   ServiceKind = "both"
	Cli    ServiceKind = "cli"
	Worker ServiceKind = "worker"
)

// Valid indicates whether the value is a known member of the ServiceKind enum.
func (e ServiceKind) Valid() bool {
	switch e {
	case API:
		return true
	case Both:
		return true
	case Cli:
		return true
	case Worker:
		return true
	default:
		return false
	}
}

// CompatibilityEdge One `requires` edge of the compatibility graph, seen from one of its
// two endpoints. `name` is the OTHER endpoint: the required service when
// the edge is read forward, the requiring service when it is read
// backward. Which direction is in force is the operation that returned
// the edge, not a field on it — a field that restates the direction
// invites a caller to treat the two responses as interchangeable, which
// is the substitution the graph exists to prevent.
type CompatibilityEdge struct {
	// Dependency How hard the edge binds. `required` — the service does not start
	// without it. `soft` — it starts and runs degraded, which is muse's
	// own `required: false` written as a word. `dev` — build and test
	// time only.
	Dependency CompatibilityEdgeDependency `json:"dependency"`

	// Name The other endpoint of the edge.
	Name string `json:"name"`

	// VersionRange The publisher's own constraint on the other endpoint's contract
	// version, in core's four-form grammar, stored verbatim. It is not
	// re-rendered, because a range the publisher wrote is a claim about
	// what they tested against and re-rendering it into an equivalent
	// form would be this registry quietly editing somebody's claim.
	VersionRange string `json:"version_range"`
}

// CompatibilityEdgeDependency How hard the edge binds. `required` — the service does not start
// without it. `soft` — it starts and runs degraded, which is muse's
// own `required: false` written as a word. `dev` — build and test
// time only.
type CompatibilityEdgeDependency string

// Dependency defines model for Dependency.
type Dependency struct {
	Name string `json:"name"`

	// Required false is a soft dependency — the service runs degraded without it.
	Required *bool `json:"required,omitempty"`

	// Version Constraint on the dependency's own contract version.
	Version *string `json:"version,omitempty"`
}

// Exposes defines model for Exposes.
type Exposes struct {
	// API Repository-relative path to the service's OpenAPI 3.1 document.
	API *string `json:"api"`

	// Events Event types this service publishes, as `<service>.<entity>.<action>`.
	Events []string `json:"events"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Language core's manifest `language` enum minus `spec`. `spec` is for
// specification-only repositories — core itself, contract-test fixtures —
// which are not services and cannot be registered.
type Language string

// Owner defines model for Owner.
type Owner struct {
	Contact *openapi_types.Email `json:"contact,omitempty"`

	// Team The accountable team, not the author.
	Team string `json:"team"`
}

// Page core's paging envelope.
type Page struct {
	HasMore bool `json:"has_more"`

	// NextCursor Opaque; null on the last page.
	NextCursor *string `json:"next_cursor"`
}

// Problem RFC 9457 problem details with core's extensions: a stable
// `https://errors.cafaye.com/<code>` type, a reserved `code`, and a
// `trace_id` that always matches the `X-Trace-Id` header. No service
// invents its own error body, so every non-2xx response — including the
// framework's own 404 and 405 — is this shape.
type Problem struct {
	Code ProblemCode `json:"code"`

	// Detail Specific to this occurrence. Clients do not parse it.
	Detail string `json:"detail"`

	// Errors Present only on 422. pantry answers 400 rather than 422, so it never sends this.
	Errors *[]map[string]interface{} `json:"errors,omitempty"`

	// Instance The request path this is about.
	Instance string `json:"instance"`
	Status   int    `json:"status"`

	// Title A fixed human-readable summary for this code; may be reworded without a version bump.
	Title   string `json:"title"`
	TraceID string `json:"trace_id"`
	Type    string `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// Readiness defines model for Readiness.
type Readiness struct {
	// Services How many services are loaded.
	Services int             `json:"services"`
	Status   ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Repository defines model for Repository.
type Repository struct {
	DefaultBranch *RepositoryDefaultBranch `json:"defaultBranch,omitempty"`

	// URL SSH remote. core's schema rejects HTTPS for a cafaye repository.
	URL        string                `json:"url"`
	Visibility *RepositoryVisibility `json:"visibility,omitempty"`
}

// RepositoryDefaultBranch defines model for Repository.DefaultBranch.
type RepositoryDefaultBranch string

// RepositoryVisibility defines model for Repository.Visibility.
type RepositoryVisibility string

// Service One registered service: its manifest, plus `kind` and `basePath`.
//
// Optional keys are omitted rather than null when the service's manifest
// omits them — `defaultBranch`, `visibility`, `contact`, `description` and a
// dependency's `version`/`required`. Two keys are always present and may be
// null, because null there is a fact rather than an absence: `exposes` is
// null when the manifest declares no contract surface, and `basePath` is
// null when the service publishes no OpenAPI document.
type Service struct {
	// BasePath The `/vN` prefix every contract path in the service's OpenAPI document
	// is under, or null when it publishes no document.
	BasePath *string `json:"basePath"`

	// Consumes Event types this service subscribes to. Empty rather than absent.
	Consumes []string `json:"consumes"`

	// Core The service's constraint on the core spec version, in core's four-form grammar.
	Core string `json:"core"`

	// Dependencies Other cafaye services this one builds on. Empty rather than absent.
	Dependencies []Dependency `json:"dependencies"`
	Description  *string      `json:"description,omitempty"`

	// Exposes The service's published surface, or null when it declares none.
	Exposes *Exposes `json:"exposes"`

	// Kind | manifest says | kind |
	// | --- | --- |
	// | `exposes.api` declared, no `consumes` | `api` |
	// | `exposes.api` declared and `consumes` non-empty | `both` |
	// | no `exposes.api`, some event work | `worker` |
	// | no contract surface, and the repository serves HTTP | `api` |
	// | no contract surface, and the repository is a binary | `cli` |
	// | no contract surface, and it is an installed artifact with no entry point | `cli` |
	//
	// The last three rows are **curated**, not derived, and they are the only
	// two curated values. A manifest that declares no contract surface cannot
	// say which one it is: `guard` (a gateway whose OpenAPI document has not
	// been written yet), `caf` (a binary) and `cafaye-ts` (a package other
	// programs import, which serves nothing and vendors six other
	// repositories' OpenAPI documents into `specs/`) declare the same absence
	// of surface, and `language` names a toolchain rather than a shape.
	//
	// A client that routes or deploys by `kind` should branch on it rather
	// than assume every entry serves HTTP: `cli` is an entry somebody installs
	// and nobody routes to.
	//
	// The third row is a value the vocabulary does not quite have a word for,
	// and the two client libraries in the fleet are currently answered
	// differently — `cafaye-ts` is a `cli` here, and the `cafaye-rb` gem is in
	// the exclusion record rather than in this list. See `DECISIONS.md` D1.
	// Neither answer changes the wire format; it changes who is listed.
	Kind ServiceKind `json:"kind"`

	// Language core's manifest `language` enum minus `spec`. `spec` is for
	// specification-only repositories — core itself, contract-test fixtures —
	// which are not services and cannot be registered.
	Language Language `json:"language"`

	// Name The cafaye namespace name; also the repository name and the event `source`.
	Name       string     `json:"name"`
	Owner      Owner      `json:"owner"`
	Repository Repository `json:"repository"`
}

// ServiceKind | manifest says | kind |
// | --- | --- |
// | `exposes.api` declared, no `consumes` | `api` |
// | `exposes.api` declared and `consumes` non-empty | `both` |
// | no `exposes.api`, some event work | `worker` |
// | no contract surface, and the repository serves HTTP | `api` |
// | no contract surface, and the repository is a binary | `cli` |
// | no contract surface, and it is an installed artifact with no entry point | `cli` |
//
// The last three rows are **curated**, not derived, and they are the only
// two curated values. A manifest that declares no contract surface cannot
// say which one it is: `guard` (a gateway whose OpenAPI document has not
// been written yet), `caf` (a binary) and `cafaye-ts` (a package other
// programs import, which serves nothing and vendors six other
// repositories' OpenAPI documents into `specs/`) declare the same absence
// of surface, and `language` names a toolchain rather than a shape.
//
// A client that routes or deploys by `kind` should branch on it rather
// than assume every entry serves HTTP: `cli` is an entry somebody installs
// and nobody routes to.
//
// The third row is a value the vocabulary does not quite have a word for,
// and the two client libraries in the fleet are currently answered
// differently — `cafaye-ts` is a `cli` here, and the `cafaye-rb` gem is in
// the exclusion record rather than in this list. See `DECISIONS.md` D1.
// Neither answer changes the wire format; it changes who is listed.
type ServiceKind string

// ServiceList A page of registered services.
type ServiceList struct {
	// Data Always an array, empty rather than absent. Sorted by name.
	Data []Service `json:"data"`

	// Page core's paging envelope.
	Page Page `json:"page"`
}

// ServiceRequiredBy The backward answer: what depends on `service`. Same edge shape as the
// forward answer with the direction reversed, and deliberately a
// DIFFERENT object — a client that confuses the two questions gets a
// type error rather than an outage.
type ServiceRequiredBy struct {
	// Data The `requires` edges pointing at the subject, ordered by the requiring service's name. Empty when nothing requires it.
	Data []CompatibilityEdge `json:"data"`

	// Service The subject — the service being depended on, echoing the path parameter.
	Service string `json:"service"`
}

// ServiceRequirements The forward answer: what running `service` needs. `data` holds only
// `requires` edges, and an edge is present only when both of its
// endpoints are visible to the caller.
type ServiceRequirements struct {
	// Data The `requires` edges, ordered by the required service's name. Empty when the service is a leaf of the graph.
	Data []CompatibilityEdge `json:"data"`

	// Service The subject — the service whose requirements these are, echoing the path parameter rather than leaving the caller to remember it.
	Service string `json:"service"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Kind Narrow to services of one kind. `api` serves HTTP and consumes
	// nothing, `worker` has no declared HTTP surface and does event work,
	// `both` serves HTTP and consumes events, and `cli` is an installed
	// artifact — a binary, or a package other programs import — rather
	// than something brought up and routed to. `api` and `cli` are also
	// the two curated values: an entry whose manifest declares no contract
	// surface is one of those two by a recorded judgement rather than by
	// derivation.
	Kind *ServiceKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Language Narrow to one implementation language. This is core's manifest
	// `language` enum minus `spec`: a specification repository is not a
	// service and cannot be a registry entry, so `?language=spec` is a
	// `400` rather than an empty list.
	Language *Language `form:"language,omitempty" json:"language,omitempty"`

	// Contract Narrow to services whose own `core` constraint shares a version with
	// this range. The comparison is range intersection, not string
	// equality: `>=0.2.0` matches a service pinned to `^0.2.0`, and
	// `^0.2.0` does not match a service pinned to `^0.1.0` because before
	// 1.0 a caret pins the minor.
	//
	// The grammar is core's four forms and nothing else: `MAJOR.MINOR.PATCH`,
	// `^`, `~` and `>=`. Anything else is a `400`.
	Contract *string `form:"contract,omitempty" json:"contract,omitempty"`

	// Limit Page size. Defaults to 25, capped at 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque base64url cursor from a previous response's
	// `page.next_cursor`. Clients must not parse it and its encoding may
	// change without notice. A cursor this service did not issue is a
	// `400` — never silently page one, which loses rows without saying so.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz Liveness
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Readyz Readiness
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
	// ListServices The official cafaye service registry
	// (GET /v1/services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)
	// GetService One registered service
	// (GET /v1/services/{name})
	GetService(w http.ResponseWriter, r *http.Request, name string)
	// ListServiceRequiredBy What depends on one service
	// (GET /v1/services/{name}/required-by)
	ListServiceRequiredBy(w http.ResponseWriter, r *http.Request, name string)
	// ListServiceRequirements What one service needs in order to run
	// (GET /v1/services/{name}/requirements)
	ListServiceRequirements(w http.ResponseWriter, r *http.Request, name string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Healthz Liveness
// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readyz Readiness
// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListServices The official cafaye service registry
// (GET /v1/services)
func (_ Unimplemented) ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetService One registered service
// (GET /v1/services/{name})
func (_ Unimplemented) GetService(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListServiceRequiredBy What depends on one service
// (GET /v1/services/{name}/required-by)
func (_ Unimplemented) ListServiceRequiredBy(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListServiceRequirements What one service needs in order to run
// (GET /v1/services/{name}/requirements)
func (_ Unimplemented) ListServiceRequirements(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "contract" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "contract", r.URL.Query(), &params.Contract, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "contract"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contract", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServiceRequiredBy operation middleware
func (siw *ServerInterfaceWrapper) ListServiceRequiredBy(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServiceRequiredBy(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServiceRequirements operation middleware
func (siw *ServerInterfaceWrapper) ListServiceRequirements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServiceRequirements(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services", wrapper.ListServices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services/{name}", wrapper.GetService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services/{name}/requirements", wrapper.ListServiceRequirements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services/{name}/required-by", wrapper.ListServiceRequiredBy)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})

	return r
}
